version: '3.8'

services:
  nextjs-app:
    build:
      context: ../services/nextjs-app
      dockerfile: Dockerfile
    container_name: chatbot-llm
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ../services/nextjs-app/.env
    environment:
      - NODE_ENV=production

  embedding-service:
    build:
      context: ../services/embedding-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - hf_cache:/root/.cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  hf_cache:
